title: "Seamus Tuohy"
description: "The personal website of Seamus Tuohy."
sourcecode: "https://github.com/seamustuohy/elationfoundation.github.io"
default_image: "http://seamustuohy.com/images/headshot_400px.JPG"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "http://seamustuohy.com"     # the base hostname & protocol for your site
baseurl: ""                   # the subpath of your site, e.g. /blog


# if you don't have any of social below, comment the line
# facebook: myfacebook
rss: feed.xml
twitter: seamustuohy
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: seamustuohy
# youtube: myyoutube
# spotify: myspotify
github: seamustuohy
medium: seamustuohy
# vimeo: myvimeo
email: hello@seamustuohy.com


# Build settings
markdown: kramdown
highlighter: rouge
